/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import com.sun.awt.AWTUtilities;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Rojeru San CL
 */
public class SplashScreen extends javax.swing.JFrame {

    SplashScreen spl = this;
    static conectar cc = new conectar();
    static Connection cn = cc.conexion();

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/splash1.png")).getImage());
        this.setLocationRelativeTo(null);
        this.progreso.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
      //  Dias_Prueba();
        startThread();
    }

    void startThread() {
        Thread hi = new Thread(new Runnable() {
            @Override
            public void run() {
                AccesoLogin ven = new AccesoLogin(spl);
                ven.setLocationRelativeTo(null);
                ven.setVisible(true);
                dispose();
            }
        });
        hi.start();
    }

//    public void Dias_Prueba() {
//        Correr corre=new Correr();
//        int id=corre.periodo_prueba_id();
//        int numero_id=15-id;
//        int numero_id2=16-id;
//        String dias_restantes=String.valueOf(numero_id);
//        String dias_restantes2=String.valueOf(numero_id2);
//        if(id==1){
//        txt.setText("Versión de prueba, "+dias_restantes+" días restantes.");
//        }
//        else{
//            if(numero_id2==0||numero_id2==-1){
//                txt.setText("Versión de prueba, ultimo día de uso");
//            }else{
//            txt.setText("Versión de prueba, "+dias_restantes2+" días restantes.");
//            }
//        }
//    }
    
    public JProgressBar getJProgressBar() {
        return progreso;
    }

    public JLabel getJLabel() {
        return texto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();
        progreso = new org.edisoncor.gui.progressBar.ProgressBarRound();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 51, 51));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("Cargando componentes...");
        texto.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 350, 30));

        progreso.setBackground(new java.awt.Color(255, 255, 255));
        progreso.setForeground(new java.awt.Color(42, 102, 142));
        getContentPane().add(progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 350, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/splash1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.edisoncor.gui.progressBar.ProgressBarRound progreso;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
