/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package respaldo_BD;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.FileVisitor;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.BasicFileAttributes;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import necesario.RSAWTUtilities;
import net.lingala.zip4j.exception.ZipException;
import principal.conectar;
import rojeru_san.complementos.RSMoveObject;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author 4L3
 */
public class WarningBackup extends javax.swing.JDialog {

    public static boolean continuar = false;

    /**
     * Creates new form ErrorAlert
     */
    public WarningBackup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        archivos = new ArrayList<>();
        jPanelRespaldo.setVisible(false);
        jPanelCargar.setVisible(false);

        RSAWTUtilities.setOpaque(this, false);
        RSUtilities.setCentrarVentana(this);
        RSMoveObject.setMoverVentana(this);

      //  txtNombre.requestFocus();
      //  txtNombre.setNextFocusableComponent(btnAceptar_respaldo);
     //   btnAceptar_respaldo.setNextFocusableComponent(btnCancelar);

        lblErrorNombre_respaldo.setVisible(false);
        lblErrorDir_respaldo.setVisible(false);
        
        lblErrorDir_cargar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        Panel_contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        rSPanelShadow1 = new rojeru_san.rspanel.RSPanelShadow();
        jPanelContenedor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new rojeru_san.RSButtonRiple();
        titulo = new javax.swing.JLabel();
        Label_Respaldo = new javax.swing.JLabel();
        Label_Carga = new javax.swing.JLabel();
        jPanelCargar = new javax.swing.JPanel();
        btnAceptar_cargar = new rojeru_san.RSButtonRiple();
        txtdir_carga = new rojeru_san.rsfield.RSTextMaterial();
        lblErrorDir_cargar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanelRespaldo = new javax.swing.JPanel();
        lblErrorNombre_respaldo = new javax.swing.JLabel();
        txtNombre = new rojeru_san.rsfield.RSTextMaterial();
        btnAceptar_respaldo = new rojeru_san.RSButtonRiple();
        txtdir = new rojeru_san.rsfield.RSTextMaterial();
        lblErrorDir_respaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setTitle("Productos");

        Panel_contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Panel_contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BACKUP.png"))); // NOI18N
        jLabel1.setText("RESPALDAR");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CARGA.png"))); // NOI18N
        jLabel2.setText("RESTAURAR");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_contenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 0, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("direccion");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/label-error-backup.png"))); // NOI18N
        jLabel5.setText("¡Debe ingresar una dirección para el respaldo!");

        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("nombre");

        jLabel6.setText("error nombre");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        Panel_contenedor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 380, 350));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(668, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(69, 87, 252));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setBackground(new java.awt.Color(69, 87, 252));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-cerrar.png"))); // NOI18N
        btnCancelar.setColorHover(new java.awt.Color(69, 87, 252));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 32, 30));

        titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("RESPALDAR / RESTAURAR");
        jPanel4.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 390, 42));

        jPanelContenedor.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        Label_Respaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BACKUP.png"))); // NOI18N
        Label_Respaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_Respaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_RespaldoMouseClicked(evt);
            }
        });
        jPanelContenedor.add(Label_Respaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 125));

        Label_Carga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CARGA.png"))); // NOI18N
        Label_Carga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Label_Carga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Label_Carga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_CargaMouseClicked(evt);
            }
        });
        jPanelContenedor.add(Label_Carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 160, 125));

        jPanelCargar.setBackground(new java.awt.Color(255, 255, 255));

        btnAceptar_cargar.setBackground(new java.awt.Color(69, 87, 252));
        btnAceptar_cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-crear.png"))); // NOI18N
        btnAceptar_cargar.setText("Cargar respaldo");
        btnAceptar_cargar.setColorHover(new java.awt.Color(173, 187, 194));
        btnAceptar_cargar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAceptar_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_cargarActionPerformed(evt);
            }
        });

        txtdir_carga.setEditable(false);
        txtdir_carga.setForeground(new java.awt.Color(0, 0, 0));
        txtdir_carga.setColorMaterial(new java.awt.Color(99, 70, 250));
        txtdir_carga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtdir_carga.setPlaceholder("Dirección de respaldo...");
        txtdir_carga.setSelectionColor(new java.awt.Color(220, 23, 111));
        txtdir_carga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdir_cargaKeyReleased(evt);
            }
        });

        lblErrorDir_cargar.setForeground(new java.awt.Color(243, 66, 53));
        lblErrorDir_cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/label-error-backup.png"))); // NOI18N
        lblErrorDir_cargar.setText("¡Debe ingresar una dirección para el respaldo!");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCargarLayout = new javax.swing.GroupLayout(jPanelCargar);
        jPanelCargar.setLayout(jPanelCargarLayout);
        jPanelCargarLayout.setHorizontalGroup(
            jPanelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCargarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar_cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorDir_cargar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdir_carga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(21, 21, 21))
        );
        jPanelCargarLayout.setVerticalGroup(
            jPanelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCargarLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdir_carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDir_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnAceptar_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelContenedor.add(jPanelCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, 390, -1));

        jPanelRespaldo.setBackground(new java.awt.Color(255, 255, 255));

        lblErrorNombre_respaldo.setForeground(new java.awt.Color(243, 66, 53));
        lblErrorNombre_respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/label-error-backup.png"))); // NOI18N
        lblErrorNombre_respaldo.setText("¡Debe ingresar un nombre para el respaldo!");

        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setColorMaterial(new java.awt.Color(99, 70, 250));
        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombre.setPlaceholder("Nombre del respaldo...");
        txtNombre.setSelectionColor(new java.awt.Color(220, 23, 111));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        btnAceptar_respaldo.setBackground(new java.awt.Color(69, 87, 252));
        btnAceptar_respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-crear.png"))); // NOI18N
        btnAceptar_respaldo.setText("Crear respaldo");
        btnAceptar_respaldo.setColorHover(new java.awt.Color(173, 187, 194));
        btnAceptar_respaldo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAceptar_respaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_respaldoActionPerformed(evt);
            }
        });

        txtdir.setEditable(false);
        txtdir.setForeground(new java.awt.Color(0, 0, 0));
        txtdir.setColorMaterial(new java.awt.Color(99, 70, 250));
        txtdir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtdir.setPlaceholder("Dirección de respaldo...");
        txtdir.setSelectionColor(new java.awt.Color(220, 23, 111));
        txtdir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdirKeyReleased(evt);
            }
        });

        lblErrorDir_respaldo.setForeground(new java.awt.Color(243, 66, 53));
        lblErrorDir_respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/label-error-backup.png"))); // NOI18N
        lblErrorDir_respaldo.setText("¡Debe ingresar una dirección para el respaldo!");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busca2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRespaldoLayout = new javax.swing.GroupLayout(jPanelRespaldo);
        jPanelRespaldo.setLayout(jPanelRespaldoLayout);
        jPanelRespaldoLayout.setHorizontalGroup(
            jPanelRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespaldoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar_respaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorNombre_respaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorDir_respaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        jPanelRespaldoLayout.setVerticalGroup(
            jPanelRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRespaldoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelRespaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDir_respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorNombre_respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnAceptar_respaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelContenedor.add(jPanelRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, 390, 330));

        rSPanelShadow1.add(jPanelContenedor, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JFileChooser fileChooser;
    private ArrayList<File> archivos;
    private File carpeta;
    
    private void btnAceptar_respaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_respaldoActionPerformed
        if (txtdir.getText().isEmpty()||txtNombre.getText().isEmpty()) {
            if(txtdir.getText().isEmpty()){
            txtdir.requestFocus();
            lblErrorDir_respaldo.setVisible(true);
        }else if(txtNombre.getText().isEmpty()){
            txtNombre.requestFocus();
            lblErrorNombre_respaldo.setVisible(true);
        }
        } else {
            continuar = true;
            Runnable runnable1 = new Runnable() {
          public void run() {
              CargandoBackup l = new CargandoBackup(new JFrame(), true);
              Backup b=new Backup();
              l.setLocationRelativeTo(WarningBackup.this);
              l.setVisible(true);
              WarningBackup.this.setEnabled(false);
              b.exportDB(txtNombre.getText(),txtdir.getText());
              WarningBackup.this.setEnabled(true);
              l.setVisible(false);
          }
        };
      Thread t1 = new Thread(runnable1);
      t1.start();
            this.dispose();
        }
        
    }//GEN-LAST:event_btnAceptar_respaldoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fileChooser = new JFileChooser(this.txtdir.getText());
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Seleccione la carpeta contenedora de la Base de Datos");
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("*", new String[]{"*"});
//        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("*.png", new String[]{"png"});
//        fileChooser.setFileFilter(filter);
//        fileChooser.setFileFilter(filter2);
        int selection = fileChooser.showOpenDialog(this);
        archivos.clear();
        switch (selection) {
            case 0:
                if (fileChooser.getSelectedFile().isDirectory()) {
                    try {
                        buscarHijos(carpeta);
                    } catch (IOException | InterruptedException ex) {
                        Logger.getLogger(WarningBackup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                        txtdir.setText(fileChooser.getSelectedFile().getPath());
                    

                } else {
                    archivos.add(fileChooser.getSelectedFile());
                    txtdir.setText(fileChooser.getSelectedFile().getAbsolutePath());
                    //   jTextField1.setText(fileChooser.getSelectedFile().getParent());
                }
                break;
            case JFileChooser.CANCEL_OPTION:
                break;
            case JFileChooser.ERROR:
                System.err.println("Error seleccionando archivos");
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        continuar = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptar_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_cargarActionPerformed
        // TODO add your handling code here:
        if (txtdir_carga.getText().isEmpty()) {
            txtdir_carga.requestFocus();
            lblErrorDir_cargar.setVisible(true);
        } else {
            continuar = true;
            Runnable runnable1 = new Runnable() {
          public void run() {
              try {
                  CargandoRespaldo l = new CargandoRespaldo(new JFrame(), true);
                  Restore r=new Restore();
                  l.setLocationRelativeTo(WarningBackup.this);
                  l.setVisible(true);
                  WarningBackup.this.setEnabled(false);
                  r.desc(txtdir_carga.getText(),"BD");
             //     Runtime.getRuntime().addShutdownHook(6);
                  WarningBackup.this.setEnabled(true);
                  l.setVisible(false);
              } catch (ZipException ex) {
                  Logger.getLogger(WarningBackup.class.getName()).log(Level.SEVERE, null, ex);
              } catch (Exception ex) {
                  Logger.getLogger(WarningBackup.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
        };
      Thread t1 = new Thread(runnable1);
      t1.start();
            this.dispose();
        }
    }//GEN-LAST:event_btnAceptar_cargarActionPerformed

    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fileChooser = new JFileChooser(this.txtdir_carga.getText());
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogTitle("Seleccione las imagenes");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.zip", new String[]{"zip"});
//        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("*.png", new String[]{"png"});
        fileChooser.setFileFilter(filter);
//        fileChooser.setFileFilter(filter2);
        int selection = fileChooser.showOpenDialog(this);
        archivos.clear();
        switch (selection) {
            case 0:
                if (fileChooser.getSelectedFile().isDirectory()) {
                    try {
                        buscarHijos(carpeta);
                    } catch (IOException | InterruptedException ex) {
                        Logger.getLogger(WarningBackup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (!archivos.isEmpty()) {
                        txtdir_carga.setText(fileChooser.getSelectedFile().getPath());
                    } else {
                        JOptionPane.showMessageDialog(null, "La carpeta seleccionada no contiene archivos válidos", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    archivos.add(fileChooser.getSelectedFile());
                    txtdir_carga.setText(fileChooser.getSelectedFile().getAbsolutePath());
                    //   jTextField1.setText(fileChooser.getSelectedFile().getParent());
                }
                break;
            case JFileChooser.CANCEL_OPTION:
                break;
            case JFileChooser.ERROR:
                System.err.println("Error seleccionando archivos");
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void buscarHijos(File file) throws IOException, InterruptedException {
        file = fileChooser.getSelectedFile();
        if (file.listFiles().length == 0 || file.listFiles() == null) {
            System.out.println("la carpeta esta vacía");
        } else {
            final Path rootDir = Paths.get(file.getAbsolutePath(), new String[0]);
            Files.walkFileTree(rootDir, new FileVisitor<Path>() {
                private Pattern pattern = Pattern.compile("^(.*?)");

                @Override
                public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes atts) throws IOException {
                    boolean matches = this.pattern.matcher(path.toString()).matches();
                    return matches ? FileVisitResult.CONTINUE : FileVisitResult.SKIP_SUBTREE;
                }

                @Override
                public FileVisitResult visitFile(Path path, BasicFileAttributes mainAtts) throws IOException {

                    boolean matches = (path.toFile().getName().endsWith(".db"));
                    if (matches) {
                        archivos.add(path.toFile());
                    }

                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult postVisitDirectory(Path path, IOException exc) throws IOException {
                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult visitFileFailed(Path path, IOException exc) throws IOException {
                    exc.getMessage();
                    return path.equals(rootDir) ? FileVisitResult.TERMINATE : FileVisitResult.CONTINUE;
                }

            });
        }
    }
    
    private void Label_RespaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_RespaldoMouseClicked
        // TODO add your handling code here:
        Label_Carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CARGA.png")));
        Label_Respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BACKUP ON.png")));
        titulo.setText("RESPALDAR");
        jPanelCargar.setVisible(false);
        jPanelRespaldo.setVisible(true);
    }//GEN-LAST:event_Label_RespaldoMouseClicked

    private void txtdir_cargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdir_cargaKeyReleased
        // TODO add your handling code here:
        if(txtdir_carga.getText().length()>0){
            lblErrorDir_cargar.setVisible(false);
        }
            
    }//GEN-LAST:event_txtdir_cargaKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        if(txtNombre.getText().length()>0){
            lblErrorNombre_respaldo.setVisible(false);
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtdirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdirKeyReleased
        // TODO add your handling code here:
        if(txtdir.getText().length()>0){
            lblErrorDir_respaldo.setVisible(false);
        }
    }//GEN-LAST:event_txtdirKeyReleased

    private void Label_CargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_CargaMouseClicked
        // TODO add your handling code here:
        Label_Carga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CARGA ON.png")));
        Label_Respaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BACKUP.png")));
        titulo.setText("RESTAURAR");
        jPanelRespaldo.setVisible(false);
        jPanelCargar.setVisible(true);
    }//GEN-LAST:event_Label_CargaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarningBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarningBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarningBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarningBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WarningBackup dialog = new WarningBackup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Carga;
    private javax.swing.JLabel Label_Respaldo;
    private javax.swing.JPanel Panel_contenedor;
    private rojeru_san.RSButtonRiple btnAceptar_cargar;
    private rojeru_san.RSButtonRiple btnAceptar_respaldo;
    private rojeru_san.RSButtonRiple btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCargar;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelRespaldo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblErrorDir_cargar;
    private javax.swing.JLabel lblErrorDir_respaldo;
    private javax.swing.JLabel lblErrorNombre_respaldo;
    private rojeru_san.rspanel.RSPanelShadow rSPanelShadow1;
    private javax.swing.JLabel titulo;
    public static rojeru_san.rsfield.RSTextMaterial txtNombre;
    public static rojeru_san.rsfield.RSTextMaterial txtdir;
    public static rojeru_san.rsfield.RSTextMaterial txtdir_carga;
    // End of variables declaration//GEN-END:variables
}
